# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d3ee998d26e146a4df7287ab31fd745"
name = "fulfilment"
application_url = "https://ca379670ca44.ngrok-free.app"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_apps,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customer_events,read_customers,write_customers,read_discovery,write_discovery,write_draft_orders,read_draft_orders,read_fulfillments,write_fulfillments,read_delivery_option_generators,write_delivery_option_generators,write_order_edits,read_order_edits,read_orders,write_orders,customer_read_orders,customer_write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
